name: Build and Test

on: [push]

env:
  MAVEN_OPTS: -Dmaven.repo.local=repository

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
    
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: repository/
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Build with Maven
      uses: maven-actions/mvn-action@0.11.0
      with:
        args: clean install
    
    - name: Test with Maven
      uses: maven-actions/mvn-action@0.11.0
      with:
        args: test
    
    - name: Publish test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/
